version: '3.8'

services:
  spleeter-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mapeia o diretório atual para /app no contêiner
    environment:
      - PYTHONUNBUFFERED=1  # Evita o buffering dos logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
